### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by biladina** [ferboiar/wrt32x#2]
Hi, can I know step by step how to install this firmware?? because I saw about UBI things that I'm not familiar with..

right now I already use openwrt from [this build](https://forum.openwrt.org/t/davidc502-wrt1200ac-wrt1900acx-wrt3200acm-wrt32x-builds/15839), which is standart image with some additional packages..

Device: Linksys Venom WRT32X
Firmware: OpenWrt SNAPSHOT r11962-b6946542f8 / LuCI Master git-20.011.66524-83c6227

**Comment by ferboiar** [comment]
if your router already has openwrt you can install this one just like you did with David's fw.

Remember to use the sysupgrade bin (*wrt32x-squashfs-sysupgrade.bin). You can do it from LUCI

But be careful, the last release available here is from February 2023 (https://github.com/ferboiar/wrt32x/releases/tag/wrt32x-ISP_NONE-2023.02.23-0043). I have moved to a Flint MT6000, so I have discontinued this project. Although you could use it to compile your own fw following https://github.com/ferboiar/wrt32x/wiki/How-to-use-this-repo-to-build-your-own-firmware

**Comment by biladina** [comment]
> if your router already has openwrt you can install this one just like you did with David's fw.
> 
> Remember to use the sysupgrade bin (*wrt32x-squashfs-sysupgrade.bin). You can do it from LUCI
> 
> But be careful, the last release available here is from February 2023 (https://github.com/ferboiar/wrt32x/releases/tag/wrt32x-ISP_NONE-2023.02.23-0043). I have moved to a Flint MT6000, so I have discontinued this project. Although you could use it to compile your own fw following https://github.com/ferboiar/wrt32x/wiki/How-to-use-this-repo-to-build-your-own-firmware

okay, thank you so much..
